Write a Python function that takes a sequence of numbers and determines whether all the numbers are different from each other.

In [1]:
a = [1,2,3,4,5,5,6]


def excer_1(a):
    if len(a) == len(set(a)):
        return True
    else:
        return False
    

excer_1(a)


False

### Write a NumPy program to test whether none of the elements of a given array are zero. 

In [2]:
import numpy as np

my_array = np.array([0,1,2,4,5,6])
my_array2 = np.array([1,2,3,4,5,6])

print(np.all(my_array))
print(np.all(my_array2))

False
True


### Write a NumPy program to test if any of the elements of a given array are non-zero

In [3]:
my_array = np.array([0,1,0,0,0,0])
my_array2 = np.array([1,2,3,4,5,6])

print(np.any(my_array))
print(np.any(my_array2))

True
True


Write a NumPy program to test element-wise for NaN of a given array.

In [4]:
my_array = np.array([np.NaN,1,0,np.NaN,0,np.NaN])

np.isnan(my_array)

array([ True, False, False,  True, False,  True])

Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives

In [7]:
array0 = np.zeros(10)
array1 = np.ones(10)
array2 = np.ones(10)*5

print(array0)
print(array1)
print(array2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


Write a NumPy program to create an array of all even integers from 30 to 70.

In [9]:
array30 = np.arange(30,71,2)

array30

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

Write a NumPy program to create a 3x3 identity matrix.

In [10]:
array_2d = np.identity(3)

array_2d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Write a NumPy program to generate a random number between 0 and 1.

In [38]:
array_randomNums = np.random.normal(0,1,1)


array_randomNums

array([-0.29606089])

Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution

In [48]:
array_randomNums15 = np.random.normal(0,1,15)

array_randomNums15

array([-2.21063485,  0.51887301,  0.89338078, -1.44619496, -0.51740402,
        0.08071481,  0.32258641,  1.49060684, -0.69448762, -1.36452607,
        0.77756473,  0.19450063, -0.629113  ,  0.43857502, -0.15140018])

Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [51]:
vec = np.arange(15,56)

print(vec)
print(vec[1:-1])

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


Write a NumPy program to create a 3X4 array and iterate over it.

In [59]:
a = np.arange(10,22).reshape(3,4)

print(a)

for i in np.nditer(a):
    print(i,end=" ")


[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
10 11 12 13 14 15 16 17 18 19 20 21 

Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.

In [63]:
b = np.linspace(10,49,5)

b

array([10.  , 19.75, 29.5 , 39.25, 49.  ])

Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

In [72]:
c = np.arange(21)

c[(c>9) & (c<16)]*= -1

c

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9, -10, -11, -12,
       -13, -14, -15,  16,  17,  18,  19,  20])

Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.

In [82]:
d = np.random.randint(0,10,5)

d

array([7, 7, 6, 2, 1])

Write a NumPy program to multiply the values of two given vectors

In [83]:
a = np.ones(5)*3
b = np.ones(5)*2

c = a*b

c

array([6., 6., 6., 6., 6.])

Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.

In [86]:
ab = np.arange(10,22).reshape(3,4)

ab

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

Write a NumPy program to find the number of rows and columns in a given matrix.

In [87]:
ab.shape

(3, 4)

Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal elements are 1, the rest are 0

In [94]:
ac = np.identity(3)
# ac = np.eye(3)


ac

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0

In [109]:
absrs = np.ones((10,10))

absrs[1:-1,1:-1] = 0

absrs

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [115]:
absd = np.diag([1,2,3,4,5])

absd

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal

In [120]:
absddd = np.zeros((4,4))

absddd[::2,1::2] = 1
absddd[1::2,::2] = 1

absddd

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

Write a NumPy program to create a 3x3x3 array filled with arbitrary values

In [123]:
abc = np.random.random((3,3,3))

abc

array([[[0.23158578, 0.2012794 , 0.5094539 ],
        [0.46471249, 0.69557837, 0.86502457],
        [0.53380074, 0.63679606, 0.20860599]],

       [[0.95033839, 0.74736413, 0.75316572],
        [0.50662467, 0.0031585 , 0.77445752],
        [0.72413026, 0.16185917, 0.16978948]],

       [[0.83126226, 0.20595679, 0.58872329],
        [0.05472899, 0.60096544, 0.32099254],
        [0.14631393, 0.94081346, 0.97655585]]])

Write a NumPy program to compute the sum of all elements, the sum of each column and the sum of each row in a given array.

In [127]:
abd = np.array([[0,1],[2,3]])

print(abd)

print(np.sum(abd))
print(np.sum(abd,axis=1))
print(np.sum(abd,axis=0))

[[0 1]
 [2 3]]
6
[1 5]
[2 4]


Write a NumPy program to compute the inner product of two given vectors

In [129]:
np.dot(abd[0],abd[1])

3